### ISSUE TITLE
Significant change in Axelarscan API /interchainchart endpoint

### ISSUE THREAD

**Issue by alexwes** [axelarnetwork/support#127]
Hi,

I noticed the data returned by the interchainChart endpoint of the Axelarscan API has changed significantly. 

Transactions and user counts have decreased by more than an order of magnitude, and cross chain volume has decreased by many multiples. 

Old data ending 03-07-2024 pulled in March 2024:
<img width="596" alt="Screenshot 2024-07-11 at 2 20 14 PM" src="https://github.com/axelarnetwork/support/assets/28934078/8823be5a-38db-4688-9029-b32f691e5a8f">

New data ending 03-07-2024 pulled in July 2024:
<img width="677" alt="Screenshot 2024-07-11 at 2 23 38 PM" src="https://github.com/axelarnetwork/support/assets/28934078/6b75c2cb-acce-4348-8448-b5332d4f045a">

The query I used has not changed since I first pulled the data in March:

```
import requests, json, pandas as pd

# The endpoint you're targeting
url = 'https://api.axelarscan.io/'

# The data you're sending in the POST request
data = '{"method":"interchainChart"}'

# Custom headers as seen in your network inspection
headers = {
    'Content-Type': 'text/plain;charset=UTF-8',  # Important: Match this with what you've observed
}

# Send the POST request
response = requests.post(url, data=data, headers=headers)

# Check the response
print('Status code:', response.status_code)

data = json.loads(response.text)['data']

df = pd.DataFrame(data)
```

**Comment by pjenviri** [comment]
Hello, can you please check whether the parameters passed are aligned with the document: https://docs.axelarscan.io/axelarscan#interchainChart ?

If yes, the results should be similar to what's shown on this page: https://axelarscan.io/interchain (with filters applied). I tested filtering data for some dates through the UI, and the results are closer to what you pulled in March 2024. (There could be some differences due to the Unix time specified in my queries on UI.)

**Comment by alexwes** [comment]
Hi PJ, I figured out the issue. I realized the endpoint changed and the method used in the code chunk above is no longer the primary form supported. I am now using the endpoint specified in the docs and it works well.

Strangely, the old endpoint still works but returns incomplete data - specifically, it is missing the GMP data. 

Thank you!
