### ISSUE TITLE
Custom Network Integration with Axelar

### ISSUE THREAD

**Issue by jesse-nhatcl** [axelarnetwork/support#140]
Hi Axelar team,

I have a few questions regarding the integration of my custom network with Axelar:

1. Is it possible to run Axelar independently, without connecting to the Axelar mainnet—essentially hosting the Axelar architecture on our own infrastructure? If so, do you offer any support or guidance for building it?

**If the above isn't possible:** 

2. What is the fee model for integrating our custom network with the Axelar mainnet?

3. Do you support a testnet environment before moving to the mainnet? If so, what is the process for joining the testnet?

4. Does Axelar support an interchain swapping UI (similar to Satellite) once we deploy to the mainnet?

Looking forward to your response.

**Comment by benjamin852** [comment]
Hey! Thanks for reaching out

1. We have an axelar devnet which is a localized instance which simulates the Axelar mainnet so you do not need to connect to mainnet directly. The devnet is called `amplifier-devnet`. More info on it can be found here in our [docs](https://docs.axelar.dev/dev/amplifier/chain-integration/integrate-a-chain/#devnet-information). To integrate with devnet you would need to fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSchD7P1WfdSCQfaZAoqX7DyqJOqYKxXle47yrueTbOgkKQDiQ/viewform)
2. There is no fee as of now for integrating with Axelar Amplifier. If you do not have your own relayer infrastructure though and need to use the Interop Labs teams relayer infra there would be a fee for that. You will also need to pool funds for the Verifiers who will be collecting rewards for verifying your cross-chain transactions. 
3. Axelar Amplifier has been live on testnet for a few weeks now. To integrate with testnet you will need to create governance proposal to get the chain integration setup there. (As opposed to with devnet where the interop labs team can simply whitelist you once you fill out the form)
4. In general, Squid router is probably your best bet here if you want to whitelist certain assets there. However, I don't think they would be available for fresh new chain connections as of yet. There will be the Interchain Token Hub so that assets on your chain are bridgeable but the Squid UI I believe will still take some more time to follow for brand new chains.
