### ISSUE TITLE
Programatically bridging tokens implementing IntechainTokenStandard.

### ISSUE THREAD

**Issue by MartinTheCzechGuy** [axelarnetwork/support#27]
Hey guys, 

I want to programmatically bridge tokens via `IInterchainTokenStandard.interchainTransfer`. What is the correct way to estimate fees for a `IInterchainTokenStandard.interchainTransfer` call? I could not find an onchain solution and my project is not using JS so I would use this endpoint `https://docs.axelarscan.io/interchain/estimateGasFee`, is that right? If so, why does it return error for some tokens, ie. request body:
`
{
	"method": "estimateGasFee",
	"sourceChain": "ethereum",
	"destinationChain": "arbitrum",
	"gasLimit": "700000",
	"gasMultiplier": "1.1",
	"minGasPrice": "0",
	"sourceTokenSymbol": "AI"
}
`

**Comment by benjamin852** [comment]
Hey @MartinTheCzechGuy. Currently there is not an out of the box onchain helper to estimate gas costs. The AxelarJS approach should work however. What is the source token with the symbol AI you're trying to query?

**Comment by MartinTheCzechGuy** [comment]
It's a random meme coin AnyInu, that implements the `InterchainTokenStandard`, https://beta.interchain.axelar.dev/ethereum/0x2598c30330D5771AE9F983979209486aE26dE875

**Comment by benjamin852** [comment]
So the issue is that the sourceTokenSymbol cannot just be any token as there are specific tokens that can be used to pay gas. If you pass in just a random token then you will receive an error. To solve this you need to use one of these specific tokens.

See [here](https://github.com/axelarnetwork/axelarjs-sdk/blob/83210e795b27a026693762ae6c7dd81ae069c882/src/libs/AxelarQueryAPI.ts#L269) the SourceChainTokenSymbol is cast as a GasToken

The GasToken must be one of [these tokens ](https://github.com/axelarnetwork/axelarjs-sdk/blob/83210e795b27a026693762ae6c7dd81ae069c882/src/constants/GasToken.ts#L5)

**Comment by MartinTheCzechGuy** [comment]
Ahh I've missed that, thank you for the help! :)
