### ISSUE TITLE
Token Ownership Claim Request

### ISSUE THREAD

**Issue by Apriloracle** [axelarnetwork/support#80]
I have submitted a claim request for the below token:

April Token
token address: 0x18719D2e1e57A1A64708e4550fF3DEF9d1074621

**Comment by benjamin852** [comment]
Hi, this forum is for dev question on using axelar protocol

**Comment by benjamin852** [comment]
Hi @Apriloracle can you please provide more context here, was unclear on what you're asking exactly. What is the token you're trying to claim? Is it stuck in a tx? Is this a custom one you built?

**Comment by benjamin852** [comment]
Thanks for the info, I am checking internally to try get this process moving for you, thanks!

**Comment by benjamin852** [comment]
Hey, quick update here we hope to have existing token ownership transfers complete by Tuesday.

**Comment by Apriloracle** [comment]
Look forward to your positive update.

**Comment by benjamin852** [comment]
Hey, @Apriloracle my aplogies for the delay here just letting you know this is still on our radar just some other updates happened this week which made this a bit tricker which is why this has not been done yet. But we are still looking to get this done and hopefully next update should be that this complete, thanks!

**Comment by Apriloracle** [comment]
ok noted.

**Comment by Apriloracle** [comment]
Hello 

Any news on this?

**Comment by benjamin852** [comment]
Hey sorry it's still being fixed. We're just in the middle of a few major roll outs which is why attention had to be diverted at the last minute here. I followed up and am told hopefully next week, but this is still on my radar and will provide you an update as soon as I have something for you, thanks and sorry again for the delay

**Comment by Apriloracle** [comment]
These continued delays are very disappointing.

**Comment by Apriloracle** [comment]
Hope this will be resolved and there won't be further delays.

**Comment by benjamin852** [comment]
confirmed this was solved, closing this ticket

**Comment by Apriloracle** [comment]
@blockchainguyy We need some help is there a way I can connect with you?
